# Generated by Django 5.0.6 on 2024-08-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgettransaction',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
